import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";

import AuthShowcase from "./auth-showcase";
import ReservationScreen from "./reservation-screen";


const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Dominion reservation</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col mt-20 gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold flex flex-col items-center justify-center tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Dominion</span> reservation
          </h1>
          <AuthShowcase sessionData={sessionData} />
          {sessionData && (
            <ReservationScreen />
          )}
        </div>
      </main>
    </>
  );
};





export default Home;
